"""Runtime profiles tuned for laptop-first experimentation."""

PROFILES = {
    "Laptop-Quick": {
        "max_epochs": 5,
        "batch_size": 32,
        "lookback_window": 24,
        "horizon_window": 1,
        "label_len": 12,
        "learning_rate": 1e-3,
        "dropout": 0.01,
        "weight_decay": 1e-4,
        "num_layers": 2,
        "hidden_feature_size": 64,
        "ntrials": 1,
        "wandb_mode": "disabled",
    },
    "Laptop-Standard": {
        "max_epochs": 20,
        "batch_size": 128,
        "lookback_window": 24,
        "horizon_window": 1,
        "label_len": 12,
        "learning_rate": 1e-3,
        "dropout": 0.01,
        "weight_decay": 1e-3,
        "num_layers": 4,
        "hidden_feature_size": 128,
        "ntrials": 1,
        "wandb_mode": "disabled",
    },
    "GPU-Standard": {
        "max_epochs": 50,
        "batch_size": 256,
        "lookback_window": 24,
        "horizon_window": 1,
        "label_len": 12,
        "learning_rate": 1e-3,
        "dropout": 0.01,
        "weight_decay": 1e-3,
        "num_layers": 4,
        "hidden_feature_size": 128,
        "ntrials": 1,
        "wandb_mode": "offline",
    },
}
